theme: jekyll-theme-time-machine
title: True-Alarm
description: An alarm that adjusts to your commute time
titles_from_headings:
  enabled: false
show_downloads: true
name: "Paul Cutter"
href: "https://github.com/pcutter1"
